'use client'
import { useEffect, useState } from "react"

import Cards from "../components/Cards"
import useRickAndMortyAPI from "../hooks/useRickAndMortyAPI"


export const metadata = {
  title: 'Characters',
  description: 'Generated by create next app',
}

export default function Characters() {
  const {
    records: characters,
    page,
    setPage,
  } = useRickAndMortyAPI()

  return (
    <>
      <button onClick={() => setPage(page + 1)}>Next Page</button>
      <Cards cards={characters} />
    </>
  )
}