'use client'
import { useReducer } from "react"

import Cards from "../components/Cards"
import useRickAndMortyAPI from "../hooks/useRickAndMortyAPI"


export const metadata = {
  title: 'Characters',
  description: 'Generated by create next app',
}

function reducer(state, action) {
  switch (action.type) {
    case 'next_page':
      return { ...state, page: state.page + 1 }
    default:
      return state
  }

}

const INITIAL_STATE = { title: 'Characters', page: 1 }

export default function Characters() {
  const [state, dispatch] = useReducer(reducer, INITIAL_STATE)

  const {
    records: characters,
    page,
    setPage,
  } = useRickAndMortyAPI()

  const handleNextPage = () => {
    dispatch({ type: 'next_page' })
    setPage(page + 1)
  }

  return (
    <>
      <h1>{state.title}</h1>
      <p>Current page: {state.page}</p> <button onClick={handleNextPage}>Next Page</button>
      <Cards cards={characters} />
    </>
  )
}